version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vollmed-db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
